# PODNAME: File::Collector

=head1 OVERVIEW

C<File::Collector> and its companion module C<File::Collector::Processor> are
base classes designed to make it easier to create custom modules for classifying
and processing a collection of files as well as generate, track and process data
related to files in the collection.

For example, let's say you need to import raw files from one directory into some
kind of repository. Let's say that files in the directory need to be filtered
and the content of the files needs to be parsed, validated, rendered and/or
changed before getting imported. Complicating things further, let's say that the
name and location of the file in the target repository is dependent upon the
content of the files in some way. Oh, and you also have to check to make sure
the file hasn't already been imported.

This kind of task can be acomplished with a series of one-off scripts that
process and import your files with each script producing output suitable for the
next script. But if such imports involve a high level of complexity, running
separate scripts for each processing stage can be slow, tedious, error-prone and
a headache to maintain and organize.

The C<File::Collector> and C<File::Collector::Processor> base modules can help
you set up a chain of modules to combine a series of workflows into a single
logical package that will make complicated file processing more robust and
testable as well as far less tedious and easier to code.

=head1 SYNOPSIS

First, create your custom class with the appropriate methods for classifying files
and setting up the processors.

  pakcage File::Collector::YourClassifier;
  use strict; use warnings;

  # This package contains your processing methods (see below)
  use File::Collector::YourClassifier::Processor;

  # The parent of this class is another File::Collector class. This is how you
  # chain your Collectors and Processors together.
  use parent File::Collector::AnotherCustomFileClassifier;

  # Add the names of your custom processor here. Processors are just a
  # collection of files with associated methods that make it convenient for
  # manipulating files and their data.
  sub _init_processors {
    my $s = shift;
    $s->SUPER::_init_processors( @_, qw ( good bad ) );
  }

  # This method is called once for each new file found. It classifies your
  # files and create objects which can be associated with your files.
  sub _classify_file {
    my $s = shift;

    # allow parent classes to classify the files first
    $s->SUPER::_classify_file;

    # Create an object and pass the name of the file to it.
    # $s->selected is automatically set to include the  the name of the file
    # getting processed so you don't have to think about it.
    my $data = SomeObject->new( $s->selected );

    # Associate the newly created object with the file
    $s->add_obj('data', $data);

    # Classify the files according to criteria you determine to add the file
    # to a processor category
    if ( $data->{has_property} ) {
      $s->_classify('good');
    } else {
      $s->_classify('bad');
    }
  }

  # The _run_processes method contains method calls to your processors
  sub _run_processes {
    my $s = shift;

    # run processes of parent classes first
    $s->SUPER::_run_processes;

    # Run some methods on files classified as "good". The "do" method is a
    # method that automatically iterates over the files in the category to make
    # it super easy to code loops.
    $s->good_files->do->modify;

    # Run some methods on files classified as "bad"
    $s->bad_files->do->fix;
    $s->bad_files->do->modify;

    # You can call methods not in the current class as long as they are defined
    # in one of your parent Processor classes.
    $s->good_files->do->move;
    $s->bad_files->do->move;
  }

Now create a Processor class to contain the methods for processing the files
or data. Note that your C<Processor> class must have the same package name as
the class using this class with "::Processor" tacked on to the end.

  use File::Collector::YourClassifier::Processor;
  use parent File::Collector::Processor;

  # This method is run once for each file
  sub modify {
    my $s = shift;

    # skip the file if it has already been processed
    next if ($s->attr_defined ( 'data', 'processed' ));

    # properties of objects added by previous Collector classes can be easily accessed
    my @values = $s->get_obj_prop ( 'header', 'needed_values' );

    # You can easily run methods on objects here, too. Here we run the
    # add_header() method on the data object and pass it
    # some values.
    $s->obj_meth ( 'data', 'add_header', \@values );
  }

  # Code for fixing "bad" files goes here.
  sub fix {
    ...
  }

Now that your classes have been created, you can classify and process the files
with one line:

   my $collector = File::Collector::YourClassifier->new('my/dir', { recurse => 0 });

   # The $collector object has methods you can call
   $collector->get_count; # returns total number of files in the collection

   # Some behind-the-scenes magic is employed by some methods to make it
   # painless to iterate over files and run methods on them.
   while ($collector->next_good_file) {
     $collector->print_short_name;
   }

=head1 DESCRIPTION

=head2 Regular Collector Methods

The methods below are found in the C<File::Collector> class. Be sure to look at the
L<File::Collector::Base> class for methods meant for use by iterators.

=method new( 'dir', 'file', ..., \%opts  )

  my $collector = File::Collector::MyClassifier->new('my/directory', { recurse => 0 } );

Creates a C<Collector> object to collect files in the argument list. An option
hash can be supplied to turn directory recursion off with C<recurse> which is
set to true by default. Once created, the C<Collector> immediately goes to work
collecting and processing the files according to the workflow you created with
your custom modules.

C<new> returns an object which contains all the files, their processing classes,
and any data you have associated with the files. This object has serveral
methods that can be used to inspect the object.

=method add_resources( 'dir', 'file' )

  $collector->add_resources( 'file1', 'dir2', ... );

Adds additional file resources to the collection and processes them. This method
accepts no option hash.

=method get_count()

  $collector->get_count;

Returns the total number of files in the collection.

=method get_files()

  my @all_files = $collector->get_files;

Returns a list of the full path of each file in the collection.

=method get_file($file)

  my $file = $collector->get_files('/full/path/to/file.txt');

Returns has reference of the data an objects associated with a file.

=method list_files_long()

Prints the full path names of each file in the collection, sorted alphabetically, to STDOUT.

=method list_files()

Same as C<list_files_long> but prints the files' paths relative to the top level
directory shared by all the files in the collections.

=head2 Private Collector Methods for Child Classes

The following methods, though private, are meant to be overridden by the child
classes of C<File::Collector> that you provide.

=method _init_processors( @_, @your_custom_file_categories )

  sub _init_processors {
    my $s = shift;
    $s->SUPER::_init_processor( @_, ( 'category_1', 'category_2' ) );
  }

Adds categories for your Collector class. Internally, this method adds a new
Processor object to the C<Collector> so that C<Processor> methods found in your
custom C<Processor> class can be run on your files. This method is run once upon
C<Collector> object construction.

This method should call the C<SUPER::_init_processors> method and pass C<@_>
to it along with your custom list of categories.

=method _classify_file()

  sub _classify_file {
    my $s = shift;
    $s->SUPER::_classify_file();

    # File classifying and analysis logic goes here
  }

Use this method to classify your files and associate objects with your files
using the methods provided by the C<Collector> class. This method is run
once for each file in the collection.

See the L<File::Collector::Base> documentation for methods for accessing and
associating information about the file which you can use inside of this method.

This method should call the C<SUPER::_classify_file> method so that any parent classes can classify and add file processors to the C<Collector> object.

=method _classify( $category_name )

This method is typically called from within the C<_classify_file> method. It
adds the file currently getting pocessed to a collection of C<$category_name>
files contained within a C<Processor> object which, in turn, belongs to the
C<Collector> object.  The C<$category_name> must match one of the processor
names provided by the C<_init_processor> methods.

=method _add_obj( $object_name, $object )

Like the C<_classify> method, this method is typically called from within the
C<_classify_file> method. It associates the object specified by C<$object> to an
arbitrary name, specified by C<$object_name>, with the file currently getting
processed.

=method _run_processes()

  sub _run_processes {
    my $s = shift;
    $s->SUPER::_run_processes();

    # Processor method calls go here
  }

Make method calls associated with the various C<Processor>s inside of the
C<_run_processes> method. Note the inclusion of the C<SUPER::_run_processes> so
method call so parent classes can run their processor methods first.

=head1 CONFIGURATION AND ENVIRONMENT

Requires no configuration files or environment variables.

=head1 DEPENDENCIES


=head1 SEE ALSO
